// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace WineApiML.Model
{
    public class ModelInput
    {
        [ColumnName("UserId"), LoadColumn(0)]
        public float UserId { get; set; }


        [ColumnName("WineId"), LoadColumn(1)]
        public float WineId { get; set; }


        [ColumnName("Rating"), LoadColumn(2)]
        public float Rating { get; set; }


    }
}
